

# This file was *autogenerated* from the file SPIDER_params.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1 = Integer(1); _sage_const_11 = Integer(11); _sage_const_2 = Integer(2); _sage_const_257 = Integer(257); _sage_const_3 = Integer(3); _sage_const_163 = Integer(163); _sage_const_32 = Integer(32); _sage_const_128 = Integer(128); _sage_const_65 = Integer(65); _sage_const_376 = Integer(376); _sage_const_256 = Integer(256); _sage_const_20 = Integer(20); _sage_const_5 = Integer(5); _sage_const_27 = Integer(27); _sage_const_500 = Integer(500); _sage_const_4 = Integer(4); _sage_const_8 = Integer(8); _sage_const_63 = Integer(63); _sage_const_64 = Integer(64); _sage_const_0 = Integer(0)
from sqisign_prism_v2_main import params, constants
from sqisign_prism_v2_main.ec import *
from two_isogenies.Theta_SageMath.utilities.supersingular import *
#SPIDER parameters

def set_spider_params(lvl):
    """
    Return parameters for SPIDER at the given level
    """

    global p, f, lb, a, rb, D_mix
    global FP_ENC_BYTES

    if lvl == _sage_const_1 :
        #p = ZZ(27*2**500 - 1)
        p = _sage_const_11  * _sage_const_2 **_sage_const_257  * _sage_const_3 **_sage_const_163  - _sage_const_1 
        f = ZZ(_sage_const_257 )
        a = ZZ(_sage_const_257 )
        b=ZZ(_sage_const_163 )
        rb = ZZ(_sage_const_32 )
        lb = ZZ(_sage_const_128 )
        
# Parameters for level 3 and 5 are still to be defined.
    elif lvl == _sage_const_3 :
        p = ZZ(_sage_const_65 *_sage_const_2 **_sage_const_376  - _sage_const_1 )
        f = ZZ(_sage_const_376 )
        a = ZZ(_sage_const_256 )
        rb = ZZ(_sage_const_20 )
        lb = ZZ(_sage_const_376 )

    elif lvl == _sage_const_5 :
        p = ZZ(_sage_const_27 *_sage_const_2 **_sage_const_500  - _sage_const_1 )
        f = ZZ(_sage_const_500 )
        a = ZZ(_sage_const_500 )
        rb = ZZ(_sage_const_32 )
        lb = ZZ(_sage_const_128 )

    else:
        raise ValueError(f"level {lvl} not recognized")

    D_mix = next_prime(_sage_const_2 **(_sage_const_4 *lb))
    FP_ENC_BYTES = _sage_const_8  * floor((log(p, _sage_const_2 ) + _sage_const_63 ) / _sage_const_64 )

    # Quaternions
    global B, O0
    global QUAT_prime_cofactor
    B = QuaternionAlgebra(-_sage_const_1 , -p)
    _i, _j, _k = B.gens()
    O0 = B.maximal_order(order_basis=(B(_sage_const_1 ), _i, (_i+_j)/_sage_const_2 , (_sage_const_1 -_k)/_sage_const_2 ))
    QUAT_prime_cofactor = next_prime(_sage_const_2 **ceil(log(p, _sage_const_2 )))

    # Elliptic Curves
    global Fp, Fp2, Fp2_i
    global E0, P0, Q0
    Fp = GF(p)
    Fp2, Fp2_i = GF(p**_sage_const_2 , name="i", modulus=[_sage_const_1 , _sage_const_0 , _sage_const_1 ]).objgen()
    E0 = EllipticCurve(Fp2, [_sage_const_1 , _sage_const_0 ])
    E0.set_order((p + _sage_const_1 ) ** _sage_const_2 )

    # Hardcoded SQIsign implementation points and endomorphisms actions
    global iota, frob
    global mat_1, mat_i, mat_ij2, mat_1k2
    mat_1 = matrix(Zmod(_sage_const_2 **f), _sage_const_2 , [_sage_const_1 , _sage_const_0 , _sage_const_0 , _sage_const_1 ])
    P0,Q0=torsion_basis(E0, _sage_const_2 **a)
    print("P0=",P0, "\n Q0=",Q0)

set_spider_params(_sage_const_1 )
'''
    if lvl == 1:
        P0 = E0(constants.Px1, constants.Py1)
        Q0 = E0(constants.Qx1, constants.Qy1)
        mat_i = matrix(Zmod(2**f), 2, constants.mat_i_1)
        mat_ij2 = matrix(Zmod(2**f), 2, constants.mat_ij2_1)
        mat_1k2 = matrix(Zmod(2**f), 2, constants.mat_1k2_1)

# Parameters for level 3 and 5 are still to be defined.
    elif lvl == 3:
        P0 = E0(constants.Px3, constants.Py3)
        Q0 = E0(constants.Qx3, constants.Qy3)
        mat_i = matrix(Zmod(2**f), 2, constants.mat_i_3)
        mat_ij2 = matrix(Zmod(2**f), 2, constants.mat_ij2_3)
        mat_1k2 = matrix(Zmod(2**f), 2, constants.mat_1k2_3)

    elif lvl == 5:
        P0 = E0(constants.Px5, constants.Py5)
        Q0 = E0(constants.Qx5, constants.Qy5)
        mat_i = matrix(Zmod(2**f), 2, constants.mat_i_5)
        mat_ij2 = matrix(Zmod(2**f), 2, constants.mat_ij2_5)
        mat_1k2 = matrix(Zmod(2**f), 2, constants.mat_1k2_5)
'''

