

# This file was *autogenerated* from the file SPIDER_signature.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1 = Integer(1); _sage_const_3 = Integer(3); _sage_const_5 = Integer(5); _sage_const_2 = Integer(2); _sage_const_0 = Integer(0); _sage_const_210 = Integer(210); _sage_const_33 = Integer(33); _sage_const_500 = Integer(500); _sage_const_4 = Integer(4); _sage_const_249 = Integer(249)
from sage.all_cmdline import *   # import sage library

_sage_const_1 = Integer(_sage_const_1 ); _sage_const_3 = Integer(_sage_const_3 ); _sage_const_5 = Integer(_sage_const_5 ); _sage_const_2 = Integer(_sage_const_2 ); _sage_const_0 = Integer(_sage_const_0 ); _sage_const_210 = Integer(_sage_const_210 ); _sage_const_33 = Integer(_sage_const_33 ); _sage_const_500 = Integer(_sage_const_500 ); _sage_const_4 = Integer(_sage_const_4 )
import hashlib
import logging
import time
logger = logging.getLogger(__name__)
logger.setLevel(logging.WARNING)
logger_sh = logging.StreamHandler()
formatter = logging.Formatter('%(name)s [%(levelname)s] %(message)s')
logger_sh.setFormatter(formatter)
logger.addHandler(logger_sh)

from SPIDER_sigma import *
from generalities import SeedTree,Node_seed,recover_leaves,parse_hashs_t_w

class SPIDER_pp(parameters):
    '''
    pp for SPIDER signature '''
    def __init__(self,q,level=_sage_const_1 ,r=_sage_const_1,t=Integer(210),w=Integer(33)):
        super().__init__(q,level,r)
        self.t=t
        self.w=w
    
    def H(self,data):
        #msg=data.encode()
        ch=parse_hashs_t_w(data, _sage_const_2 , self.t, self.w)
        ch=[ZZ(mod(ch[i]+_sage_const_1 ,_sage_const_2 )) for i in range(self.t)]
        return ch



def SPIDER_sign(pp,pk,sk,msg):
    print("SPIDER signing process")
    E=pk
    phi=sk
    t=pp.t
    lb=pp.lb
    size=Integer(_sage_const_2 **lb)
    #t0_seed=time.time() 
    val_seed_root=ZZ.random_element(size)
    seed_root=Node_seed(val_seed_root,parent=None,left_child=None,right_child=None,h=_sage_const_0 ,i=_sage_const_0 ,nb_leaves=t)
    seed_tree=SeedTree(seed_root,t,lb)
    seed_leaves=seed_tree.leaves()
      
    seeds=[int.from_bytes(leaf.value) for leaf in seed_leaves]
    #t1_seed=time.time()
    #print(f'Seed generation time: {t1_seed-t0_seed:.3f} s')
    state=[]
    data=E.j_invariant().to_bytes()
    #t0_com=time.time()
    P,Q=TorsionBasis(E)
    coms=[sigma_Rd_Commit(pp,E,phi,seeds[i],P,Q) for i in range(t)]
    [state.append(coms[i][_sage_const_1 ]) for i in range(t)]
    #[data=data+coms[i][_sage_const_0 ].j_invariant().to_bytes() for i in range(t)]
    
    for i in range(t):
     #   com_i=sigma_Rd_Commit(pp,E,phi,seeds[i],P,Q)
      #  state.append(com_i[_sage_const_1 ])
        data+=coms[i][_sage_const_0 ].j_invariant().to_bytes()      #preferable to use the A- coeff?
    
    msg=msg.encode()
    data+=msg
    ch=pp.H(data)
    #t0_resp0=time.time()
    seed_internal=seed_tree.releaseSeed(ch,_sage_const_0 )
    #t1_resp0=time.time()
    #print(f'Response_0 time: {t1_resp0-t0_resp0:.3f} s')
    resp={}
    #t0_resp1=time.time()
    resp1=[(i,sigma_Rd_Response(state[i],_sage_const_1 )) for i in range(t) if ch[i]==_sage_const_1 ]
    [resp.update({r[Integer(0)]:r[Integer(1)]}) for r in resp1]
    #for i in range(t):
     #   if ch[i]==_sage_const_1 :
      #      resp[i]=sigma_Rd_Response(state[i],_sage_const_1 )
    #t1_resp1=time.time()
    #print(f'Response_1 time: {t1_resp1-t0_resp1:.3f} s\n \n')

    return ch,seed_internal,resp

def SPIDER_vrify(pp,pk,msg,sign):
    print("SPIDER verification process")
    E=pk
    t=pp.t
    a=pp.a/_sage_const_2 
    lb=pp.lb
    ch,seed_internal,resp=sign
    seeds_0=recover_leaves(seed_internal,ch,_sage_const_0 ,lb)
    ct=_sage_const_0 
    for seed in seeds_0:
        for i in range(ct,t):
            if ch[i]==_sage_const_0 :
                resp[i]=seed
                ct=i+_sage_const_1 
                break
    assert len(resp)==t
    P,Q=TorsionBasis(E)
    data=E.j_invariant().to_bytes()
    for i in range(t):
        if ch[i]==_sage_const_0 :
            seed=int.from_bytes(resp[i])
            s_u=pp.PRNG(seed)
            Pu,Qu=_sage_const_2 **a*P, _sage_const_2 **a*Q
            Ru=Pu+s_u[_sage_const_0 ]*Qu
            psi0=E.isogeny(Ru,algorithm="factored")
            j1=psi0.codomain().j_invariant()
            data+=j1.to_bytes()
        else:
            E1,_,_=resp[i]
            assert sigma_Rd_Verify(pp,E,E1,_sage_const_1 ,resp[i])
            j1=E1.j_invariant()
            data+=j1.to_bytes()
    msg=msg.encode()
    data+=msg
    return pp.H(data)==ch




