

# This file was *autogenerated* from the file test_qlapoti.sage
from sage.all_cmdline import *   # import sage library

_sage_const_5 = Integer(5); _sage_const_2 = Integer(2); _sage_const_248 = Integer(248); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0)
from Qlapoti_main.sage_implementation.ideal_to_isogeny.quaternion_helpers.helpers import *
from Qlapoti_main.sage_implementation.ideal_to_isogeny.theta_isogenies.product_isogeny import *
from Qlapoti_main.sage_implementation.applications.PRISM.precomputations_PRSIM import *
from Qlapoti_main.sage_implementation.ideal_to_isogeny.ideal_to_isogeny_qlapoti import *
from Qlapoti_main.sage_implementation.applications.PRISM.params import *
from Qlapoti_main.sage_implementation.applications.PRISM.PRISM_sign import *
#from POKE_PKE_main.utilities.supersingular import *
#from POKE_PKE_main.montgomery_isogenies.kummer_isogeny import *

p=_sage_const_5 *_sage_const_2 **_sage_const_248  - _sage_const_1 
e=_sage_const_248 

B = QuaternionAlgebra(-_sage_const_1 , -p) 
i, j, k = B.gens()
O0 = B.quaternion_order([_sage_const_1 , i, (i + j) / _sage_const_2 , (_sage_const_1  + k) / _sage_const_2 ])
F = GF(p**_sage_const_2 , name="i", modulus=[_sage_const_1 , _sage_const_0 , _sage_const_1 ])
E0 = EllipticCurve(F, [_sage_const_1 , _sage_const_0 ])
E0.set_order((p + _sage_const_1 ) ** _sage_const_2 )
#print(E0)

#p2=p**2
#N=p2.next_prime()
#print("N= ",N)
N = next_prime(randint(p, p**_sage_const_2 ))

O_N = O_mod_N(O0, N)
J=O_N.random_ideal()
mu1, mu2, d1, d2, θ, N1, I, betaij, e =qlapoti(J, e, odd_norm_output=True)

print("mu1=", mu1)
print("mu2= ",mu2)
print("theta= ",θ)
print("theta=mu1*mu2.conjugate/N", θ==mu2*mu1.conjugate()/N1)
print("N1/N=",round(N1**_sage_const_5 /N,_sage_const_5 ))

